<? $thispage = "participate"; ?>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
"http://www.w3.org/TR/html4/loose.dtd">
<HTML>
 <HEAD>
  <TITLE>Participate and make a difference | UC is a new initiative to channel investments to Education, Health and Energy & Environmental services sectors</TITLE>
  <meta http-equiv="content-type" content="text/ html;charset=utf-8">
  <META NAME="Description" CONTENT="Participate and make a difference -- UC is a new initiative to channel investments to Education, Health and Energy&Environmental services sectors, in order to improve access to these services especially for the poor. These sectors need a much larger infusion of capital of various kinds including Financial, Intellectual and Social Capital.">
  <link rel="stylesheet" type="text/css" href="css/main.css">
  </HEAD>
 <BODY>
 
<!--wrapper-->
<div id="wrapper">
 
<div id="header"><!--header-->
<img src="uc-logo.jpg" />
</div><!--#header-->

<!--navbar-->
<?php include 'navbar.php' ;?>
<!--#navbar-->

<!--maincontentarea-->
<div id="content-main">
<h1>Participate</h1>
<p><b>Critique our Work</b>: We welcome you to read about our work, visit us and tell us how we can do it better. Your inputs could help to generate greater social returns for the resources that we apply.</p>
<p><b><a href="uccertificates.php">PostPay and Contribute to Results</a></b>: You are invited to Post Pay and Contribute to certified results generated by UC. <a href="uccertificates-acquired.php">Click here</a> to see Certificates which have already been acquired.</p>
<p><a href="http://www.appgadgets.com/ereferral/form/eReferalVisitor.jsp"><b>Spread the Word:</b></a> You may share information about UC and its work to individuals and organisations for whom UC's work may be of interest.</p>
<p><a href="http://www.creator.zoho.com/gunaranjan/zero-waste/form-perma/UC_Project_Suggestion/RyX46HKvkgWyNPnYtK1NstaJpWRdhYZCdkmnuzzJF1N7Uzn0Q0Ja5nYQhPef1xyXGMP43DEfYtAZxSR5u8vuFd2mp1XfdYTBqe2u/"><b>Help us to reach out:</b></a> Individuals and Organisations are welcome to give inputs to UC, to target investments within the framework of UC, for people with least access to services targeted by UC. UC would do study the inputs, to help decide whether it can undertake the project based on its resources and capability.</p>
<p><a href="http://creator.zoho.com/gunaranjan/uc-customer-feedback/form-perma/Join_us/nt8m1VMkCSbK6YrGCkYpC5jmEvbnn2MuEZnmMwdKyzeJOOf9pB8wSzB4pgjGkv02WTE2dKGShXv78kTkOVvtstszhWVj2CZv8AYg/"><b>Join us:</b></a> We invite volunteers to get involved in some of the ongoing and planned activities listed below. We also would like to invite college students doing courses in related fields to undertake projects with us on relevant activities from the below list. </p>

<!--#maincontentarea-->

<!--footer-->
<? include 'footer.php' ; ?>
<!--#footer-->

 </div>
 <!--#wrapper-->

 </BODY>
</HTML>